"""
Build script to create Windows executable using PyInstaller
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path


def clean_build_directories():
    """Clean previous build directories"""
    directories_to_clean = ['build', 'dist', '__pycache__']
    
    for dir_name in directories_to_clean:
        if os.path.exists(dir_name):
            print(f"Cleaning {dir_name}...")
            shutil.rmtree(dir_name)
    
    # Clean spec files
    for spec_file in Path('.').glob('*.spec'):
        print(f"Removing {spec_file}...")
        spec_file.unlink()


def build_executable():
    """Build the executable using PyInstaller"""
    
    # Main script path
    main_script = os.path.join('cash_register_monitor', 'main.py')
    
    # Icon path
    icon_path = os.path.join('cash_register_monitor', 'icons', 'connected.ico')
    
    # PyInstaller command
    cmd = [
        'pyinstaller',
        '--onefile',                    # Create a single executable file
        '--windowed',                   # Don't show console window
        '--name=CashRegisterMonitor',   # Executable name
        f'--icon={icon_path}',         # Application icon
        '--add-data=cash_register_monitor/icons;icons',  # Include icon files
        '--hidden-import=pystray._win32',  # Include hidden imports
        '--hidden-import=PIL._tkinter_finder',
        '--clean',                      # Clean cache
        main_script
    ]
    
    print("Building executable with PyInstaller...")
    print(f"Command: {' '.join(cmd)}")
    
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        print("Build successful!")
        print("Output:", result.stdout)
        
        # Check if executable was created
        exe_path = os.path.join('dist', 'CashRegisterMonitor.exe')
        if os.path.exists(exe_path):
            print(f"Executable created: {exe_path}")
            print(f"File size: {os.path.getsize(exe_path) / 1024 / 1024:.1f} MB")
            return True
        else:
            print("ERROR: Executable not found in expected location")
            return False
            
    except subprocess.CalledProcessError as e:
        print("Build failed!")
        print("Error output:", e.stderr)
        return False
    except FileNotFoundError:
        print("ERROR: PyInstaller not found. Install it with: pip install pyinstaller")
        return False


def create_installer_script():
    """Create a simple NSIS installer script"""
    
    nsis_script = '''
; Cash Register Monitor Installer Script
; Generated by build script

!define APP_NAME "Cash Register Monitor"
!define APP_VERSION "1.0.0"
!define APP_PUBLISHER "Nima Solutions"
!define APP_EXE "CashRegisterMonitor.exe"

Name "${APP_NAME}"
OutFile "CashRegisterMonitor_Setup.exe"
InstallDir "$PROGRAMFILES\\${APP_PUBLISHER}\\${APP_NAME}"
RequestExecutionLevel admin

Page directory
Page instfiles

Section "Install"
    SetOutPath $INSTDIR
    File "dist\\${APP_EXE}"
    
    ; Create uninstaller
    WriteUninstaller "$INSTDIR\\Uninstall.exe"
    
    ; Create Start Menu shortcut
    CreateDirectory "$SMPROGRAMS\\${APP_PUBLISHER}"
    CreateShortCut "$SMPROGRAMS\\${APP_PUBLISHER}\\${APP_NAME}.lnk" "$INSTDIR\\${APP_EXE}"
    CreateShortCut "$SMPROGRAMS\\${APP_PUBLISHER}\\Uninstall ${APP_NAME}.lnk" "$INSTDIR\\Uninstall.exe"
    
    ; Registry entries for Add/Remove Programs
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayName" "${APP_NAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "UninstallString" "$INSTDIR\\Uninstall.exe"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "Publisher" "${APP_PUBLISHER}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}" "DisplayVersion" "${APP_VERSION}"
SectionEnd

Section "Uninstall"
    Delete "$INSTDIR\\${APP_EXE}"
    Delete "$INSTDIR\\Uninstall.exe"
    RMDir "$INSTDIR"
    
    Delete "$SMPROGRAMS\\${APP_PUBLISHER}\\${APP_NAME}.lnk"
    Delete "$SMPROGRAMS\\${APP_PUBLISHER}\\Uninstall ${APP_NAME}.lnk"
    RMDir "$SMPROGRAMS\\${APP_PUBLISHER}"
    
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_NAME}"
SectionEnd
'''
    
    with open('installer.nsi', 'w') as f:
        f.write(nsis_script)
    
    print("Created installer.nsi script")
    print("To create installer, install NSIS and run: makensis installer.nsi")


def main():
    """Main build function"""
    print("=== Cash Register Monitor Build Script ===")
    
    # Check if we're in the right directory
    if not os.path.exists('cash_register_monitor'):
        print("ERROR: cash_register_monitor directory not found!")
        print("Make sure you're running this script from the project root directory.")
        sys.exit(1)
    
    # Check if PyInstaller is available
    try:
        subprocess.run(['pyinstaller', '--version'], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("PyInstaller not found. Installing...")
        try:
            subprocess.run([sys.executable, '-m', 'pip', 'install', 'pyinstaller'], check=True)
        except subprocess.CalledProcessError:
            print("ERROR: Failed to install PyInstaller")
            sys.exit(1)
    
    # Clean previous builds
    clean_build_directories()
    
    # Build executable
    if build_executable():
        print("\\n=== Build Complete ===")
        print("Executable location: dist/CashRegisterMonitor.exe")
        
        # Create installer script
        create_installer_script()
        
        print("\\nNext steps:")
        print("1. Test the executable: dist/CashRegisterMonitor.exe")
        print("2. (Optional) Create installer using NSIS: makensis installer.nsi")
        
    else:
        print("\\n=== Build Failed ===")
        sys.exit(1)


if __name__ == "__main__":
    main()